---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
  config:
    min: 1
    max: 
    use_select: true
    source:
      type: simple
    options:
    - Breakfast
    - Soups and a Sandwich
    - Salads
    - Appetizers
    - Pasta
    - Main Dishes
    - Side Dishes
    - Desserts
pages:
- site/content/blog/asparagus-soup.md
- site/content/blog/baba-ganoush.md
- site/content/blog/baby-back-pork-ribs.md
- site/content/blog/beet-salad.md
- site/content/blog/biscuits-and-gravy.md
- site/content/blog/broccoli-and-anchovy-pasta.md
- site/content/blog/bruchetta.md
- site/content/blog/caesar-salad.md
- site/content/blog/cauliflower-soup.md
- site/content/blog/chicken-and-broccoli.md
- site/content/blog/chicken-with-basil-cream-and-orzo.md
- site/content/blog/classic-caesar-salad-dressing.md
- site/content/blog/classic-chicken-soup-with-rosemary.md
- site/content/blog/coconut-curry-pumpkin-soup.md
- site/content/blog/corn-chowder.md
- site/content/blog/corn-salad-with-tomatoes-feta-and-mint.md
- site/content/blog/country-lentil-soup.md
- site/content/blog/cranberry-almond-broccoli-salad.md
- site/content/blog/cuban-black-bean-soup.md
- site/content/blog/cucumber-soup.md
- site/content/blog/dolmathes.md
- site/content/blog/dutch-babies.md
- site/content/blog/eggplant-caprese-salad.md
- site/content/blog/eggplant-pasta.md
- site/content/blog/french-toast.md
- site/content/blog/gazpacho.md
- site/content/blog/ginger-cucumber-salad-with-scallops.md
- site/content/blog/gnocchi-with-creamy-herbed-tomato-sauce.md
- site/content/blog/greek-lentil-soup.md
- site/content/blog/greek-meatballs.md
- site/content/blog/grilled-vegetable-sandwich.md
- site/content/blog/huevos-rancheros.md
- site/content/blog/marinara-sauce-with-meat.md
- site/content/blog/mediterranean-sausage-and-pesto-soup.md
- site/content/blog/moqueca-brazilian-fish-stew.md
- site/content/blog/moussaka.md
- site/content/blog/mr.b-s-chicken-soup.md
- site/content/blog/mushroom-barley-soup-with-tomatoes.md
- site/content/blog/mushroom-cream-sauce.md
- site/content/blog/onion-tarte.md
- site/content/blog/paella-valencia.md
- site/content/blog/pasta-carbonara.md
- site/content/blog/patricia-pasta.md
- site/content/blog/pesto.md
- site/content/blog/pollo-con-arroz.md
- site/content/blog/pomodoro.md
- site/content/blog/red-clam-sauce.md
- site/content/blog/risotto.md
- site/content/blog/roasted-chicken-with-greek-rice.md
- site/content/blog/rosemary-chicken.md
- site/content/blog/rosemary-garlic-ground-lamb-and-potatoes.md
- site/content/blog/sausage-quiche.md
- site/content/blog/seafood-pasta.md
- site/content/blog/shakshuka-with-mozzarella-mushroom-and-eggplant-aka-breakfast-for-dinner.md
- site/content/blog/shrimp-salad.md
- site/content/blog/spanakopita.md
- site/content/blog/spanish-mussels-with-tomatoes.md
- site/content/blog/spanish-potato-tomato-soup.md
- site/content/blog/spanish-tortilla.md
- site/content/blog/spinach-omelette.md
- site/content/blog/sweet-potato-apple-and-red-lentil-soup.md
- site/content/blog/tandoori-masala-salmon-steaks.md
- site/content/blog/tortellini-and-sausage-soup.md
- site/content/blog/vegetable-soup.md
