---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
  config:
    min: 1
    max: 
    use_select: true
    source:
      type: simple
    options:
    - Breakfast
    - Soups and a Sandwich
    - Salads
    - Appetizers
    - Pasta
    - Main Dishes
    - Side Dishes
    - Desserts
pages:
- site/content/blog/biscuits-and-gravy.md
- site/content/blog/classic-chicken-soup-with-rosemary.md
- site/content/blog/cuban-black-bean-soup.md
- site/content/blog/dutch-babies.md
- site/content/blog/french-toast.md
- site/content/blog/gazpacho.md
- site/content/blog/huevos-rancheros.md
- site/content/blog/mediterranean-sausage-and-pesto-soup.md
- site/content/blog/moqueca-brazilian-fish-stew.md
- site/content/blog/mr.b-s-chicken-soup.md
- site/content/blog/sausage-quiche.md
- site/content/blog/shakshuka-with-mozzarella-mushroom-and-eggplant-aka-breakfast-for-dinner.md
- site/content/blog/spanish-potato-tomato-soup.md
- site/content/blog/spanish-tortilla.md
- site/content/blog/spinach-omelette.md
- site/content/blog/sweet-potato-apple-and-red-lentil-soup.md
