---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
  config:
    min: 1
    max: 
    use_select: true
    source:
      type: simple
    options:
    - Breakfast
    - Soups and a Sandwich
    - Salads
    - Appetizers
    - Pasta
    - Main Dishes
    - Side Dishes
    - Desserts
pages:
- site/content/blog/testing.md
